
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axkfeoivkpsvjmewqndu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4a2Zlb2l2a3BzdmptZXdxbmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTEzMjUsImV4cCI6MjA2MzMyNzMyNX0.IGFWOswzkn-weJv-6GIm8tfR6iFPYeqTJ-0M911uBlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure Supabase client with proper WebSocket settings for browser
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
